name: UI continuous integration

on:
  push:
    branches: [master]
    paths:
      - ui/**
  pull_request:
    branches: [master]
    paths:
      - ui/**

defaults:
  run:
    shell: bash
    working-directory: ui

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - run: npm test
      - run: npm run lint
